---
title: "Barra Bonita"
output: html_document
---


#Libraries
```{r}
library(dplyr)
library(ggplot2)
library(leaps)
library(caret)
library(lubridate)
library(mosaicData)
library(glmnet)
library(forecast)
library(scatterplot3d)
library(car)
library(rgl)
library(GGally)
```

**Data Source** The data comes from 

```{r}
daily_aggregate <- read.csv("/home/ana/Documents/IMA Math Boot camp/ima2021_project-main/Data/2016_2020/aggragate_daily_data.csv")

```

```{r}
#change the date format
daily_aggregate = daily_aggregate %>%
  mutate(year= year(date), month = month(date), day= day(date))

daily_aggregate = daily_aggregate %>%
  mutate(month_day = 31*(month-1) + day)

daily_aggregate %>%
  ggplot(aes(x = month_day, y=water_level, color=factor(year)))+
  geom_line()

```
```{r}
daily_aggregate = daily_aggregate %>%
  mutate(year_month = 12*year + month)


daily_aggregate %>%
  ggplot(aes(x = year_month, y=water_level, color=factor(year)))+
  geom_line()

```
  
  
**Visualizing data**

```{r}

#affluent energy vs year_month
daily_aggregate %>%
  ggplot(aes(x = year_month, y = affluent_natural_energy_southeast ))+
  geom_smooth()

#affluent energy vs energy generated
daily_aggregate %>%
  ggplot(aes(x = affluent_natural_energy_southeast, y = energy_generated))+
  geom_point(alpha = 0.5, color = "blue")+
  geom_smooth(method = "lm", color = "black")

#demand vs energy generated
daily_aggregate %>%
  ggplot(aes(x = maximum_demand, y = energy_generated))+
  geom_point(alpha = 0.5, color = "orange")+
  geom_smooth(method = 'lm', color = "black")

#affluent energy vs demand
daily_aggregate %>%
  ggplot(aes(x = affluent_natural_energy_southeast, y = maximum_demand))+
  geom_point(alpha = 0.5, color = "purple")+
  geom_smooth(method = "lm", color = "black")


```

**Forecast**

```{r}

#Shows the level of water 
daily_aggregate = daily_aggregate %>% arrange(year_month) 
y=ts(daily_aggregate$water_level, start=2016,frequency = 12)
a1 <- subset(y, end = 48)
a2 <- subset(y, start = 49)
y=a1
ggtsdisplay(y)
ggtsdisplay(diff(y))
```

```{r}
auto.arima(y)
Model = Arima(y, c(0,1,0), c(1,1,0))
checkresiduals(Model)
Model

autoplot(forecast(Model, 12))+autolayer(a2)
```

**Energy generated vs rain vs max temperature daily**
```{r}
#Importing weather information

weather <- read.csv("/home/ana/Documents/IMA Math Boot camp/ima2021_project-main/Data/historic_weather.csv")
weather[is.na(weather)] <- 0

daily_weather <- weather %>%
  group_by(date) %>%
  summarise( rain = sum(rain_mm), temp_max = max(temp_max), temp_min = min(temp_min))

#change the date format
daily_weather = daily_weather %>%
  mutate(year= year(date), month = month(date), day= day(date))

daily_weather = daily_weather %>%
  mutate(month_day = 31*(month-1) + day)

#merge and clean
DF <- merge(daily_weather, daily_aggregate, by="month_day")
DF = DF %>%
  select( year.x, month.x, year_month, month_day,  energy_generated, rain, temp_max,  temp_min, maximum_demand, volume_used)

```


```{r}
# Visualizing rain, daily.
DF %>%
  ggplot(aes(x = month_day, y = rain, color=factor(year.x)))+
  geom_line()

# Visualizing temperature, daily.
DF %>%
  ggplot(aes(x = month_day, y = temp_max, color=factor(year.x)))+
  geom_line()

# Rain vs energy generated
DF %>%
  ggplot(aes(x = rain, y = energy_generated))+
  geom_point(alpha = 0.5, color = "purple")+
  geom_smooth(method = "lm", color = "black")

#Rain vs volume used
DF %>%
  ggplot(aes(x = rain, y = volume_used))+
  geom_point(alpha = 0.5, color = "purple")+
  geom_smooth(method = "lm", color = "black")

```
```{r}
ggpairs(DF[,5:10], aes(alpha = 0.4))
```

**Energy generated vs rain vs max temperature Monthly**
```{r}

montly_weather <- DF %>%
  group_by(year_month) %>%
  summarise(energy_generated =  mean(energy_generated), rain = mean(rain), temp_max = mean(temp_max), temp_min = mean(temp_min), maximum_demand = mean(maximum_demand), volume_used = mean(volume_used) )

# Visualizing rain, montly.
montly_weather %>%
  ggplot(aes(x = year_month, y = rain, color= "blue"))+
  geom_line()

# Visualizing temperature, daily.
montly_weather %>%
  ggplot(aes(x = year_month, y = temp_max))+
  geom_line()

# Rain vs energy generated
montly_weather %>%
  ggplot(aes(x = rain, y = energy_generated))+
  geom_point(alpha = 0.5, color = "orange")+
  geom_smooth(method = "lm", color = "black")

#Rain vs volume used
montly_weather %>%
  ggplot(aes(x = rain, y = volume_used))+
  geom_point(alpha = 0.5, color = "blue")+
  geom_smooth(method = "lm", color = "black")

```

```{r}
ggpairs(montly_weather[,2:7], aes(alpha = 0.4))
```
